# Generated by Django 3.0.3 on 2020-03-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journal', '0002_comment_reply'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='target',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
